### ISSUE TITLE
"negate the multiline regex" checkbox on Matcher app does not stay checked when you reload the page.

### ISSUE THREAD

**Issue by lonsun** [stoerr/GrokConstructor#1]
Firstly, thanks for building this.  It works pretty well and I think is better than others I have found as it allows you to enter multiple log lines to test against.

To recreate the issue:

-Go to http://grokconstructor.appspot.com/do/match
-(Optional) Enter a log to match, pattern, and multiline pattern.
-Check the "negate the multiline regex" checkbox.
-Click on "Go!" button near the top of the page.
-Issue:  The checkbox is no longer checked when the results page loads.  This means that for each subsequent test you need to check that box again if you want to negate the multiline pattern.

**Comment by stoerr** [comment]
Thanks for the excellent bugreport! Fixed & Fix deployed.

**Comment by lonsun** [comment]
NP - thanks!
