### ISSUE TITLE
HAPROXYHTTPBASE, unknown grok pattern name

### ISSUE THREAD

**Issue by karatedog** [stoerr/GrokConstructor#10]
According to  logstash-patterns-core/patterns/haproxy there is a HAPROXYHTTPBASE pattern, but testing this on http://grokconstructor.appspot.com/do/match shows an error:
"This grok pattern has an unknown name HAPROXYHTTPBASE : %{HAPROXYHTTPBASE}"
Extracting HAPROXYHTTPBASE's content and using that as a patter works fine.

**Comment by stoerr** [comment]
Thank you for your report; this should work now.
