### ISSUE TITLE
Matcher automatically appends a space

### ISSUE THREAD

**Issue by kidmose** [stoerr/GrokConstructor#16]
I'm using the matcher (http://localhost:9090/do/match#result) against a single log line. 
It seems to me that pressing the "Go!" button appends a space to whats found in the pattern text area, corrupting the pattern. 

Firefox 45, linux mint 17.2 in virtualbox on windows 7, commit c8bd1aa88938ae6e073026f127bbced4dcbe4a34

**Comment by stoerr** [comment]
Sorry, I can't reproduce this problem. Can you please specify exactly what you put into the matcher form to reproduce this, preferably on http://grokconstructor.appspot.com/do/match ? Please be aware that Windows often appends a space when you do copy and paste - perhaps this is your problem. I tried just putting "foo" (without quotes) into both the log lines and pattern field - if you were right this wouldn't match, but it does.

**Comment by kidmose** [comment]
Ok, so 2 minutes ago I could reproduce and as I start writing down detailed steps I can't.
I'll close this but include the following details for posterity/if this reappears.

---

I'm seing the issue when running GrokConstructor locally, without any modifications.
I confirm that I **can not** reproduce the problem on http://grokconstructor.appspot.com/do/match#result but only locally.
I paste, parse successfully and then I fail to parse the second time, without pasting and without modifying any fields. I pay attention to added spaces when pasting, so I would be surprised if that's the issue. 
1. git clone https://github.com/stoerr/GrokConstructor.git
2. cd GrokConstructor
3. git checkout c8bd1aa
4. mvn3 clean install
5. mvn3 appengine:devserver
6. firefox -> localhost:9090 -> matcher
7. Enter log lines: `01-01-2000 12:13:14 2AD4 PACKET  0000009139486150 TCP Rcv 123.123.123.123  dde9   ? [0001   D   NOERROR] A      (10)lala(4)foo(4)example(3)com(0)`
8. Enter pattern: `%{DATESTAMP:timestamp} %{WORD:thread_id} %{WORD:context}\s %{WORD:internal_packet_id} (?<tcp_udp>UDP|TCP) (?<snd_rcv>Rcv) %{IP:remote_ip}\s+%{BASE16NUM:xid} (?<query_response>[R ]) (?<opcode>[QNU?]) \[%{BASE16NUM:flags_hex}\s+(?<flags_charcode>A?T?D?R?)\s+%{WORD:resp_code}\]\s+%{WORD:question_type}\s+(?<question_name>[a-zA-Z0-9()-_]+)`
9. press "go" and note that the pattern matches
10. press "go" again
11. note that pattern doesn't match and that one space was appended to the pattern field.
12. Each time "go" is pressed, another space is added to the pattern
