### ISSUE TITLE
enclosing pattern in quotes causes bad behavior

### ISSUE THREAD

**Issue by davecampbell** [stoerr/GrokConstructor#20]
i was testing a big pattern, and had the whole thing in quotes, as it was coming from a logstash filter.

i kept getting all sorts of match fails, but when i simply removed the quotes from beginning and end of line, it worked perfectly.

i spent maybe 2 hours going through all sorts of dead-ends.

would it be possible to mention in the prompt to NOT contain the pattern in quotes, or could your tool simply recognize that and remove them?

thanks - cool tool.

**Comment by stoerr** [comment]
I'm sorry to hear that it was so difficult for you. Yes, it would be sensible to have some functionality to quote or unquote the pattern. I don't see how I could do this an easy way. Probably this needs some Javascriptish buttons, and I currently don't have the time to do that. Of course, if someone could make a suggestion... For now I just extended the field description, and leave this as a possible enhancement.
