### ISSUE TITLE
How to skip some part of line in grok

### ISSUE THREAD

**Issue by shinesk** [stoerr/GrokConstructor#23]
I have just started using grok for logstash and I am trying to parse my log file using grok filter. 
My logline is something like below

03-30-2017 13:26:13 [00089] TIMER XXX.TimerLog: entType [organization], queueType [output], memRecno = 446323718, audRecno = 2595542711, elapsed time = 998ms

I want to capture only initial date time stamp , entType [organization],  and elapsed time = 998ms. 
Howerver looks like I have to match pattern for every word and number in the line. Is there a way I can skip it ? I tried to look everywhere but couldn't find anything. Kindly help.

**Comment by stoerr** [comment]
Sorry, this isn't an issue of grok constructor, and I can't give grok support. Grok works with regular expressions, and you can do such things with regular expressions, but I don't have the time to help everybody individually.
