### ISSUE TITLE
Different behavior "Kibana Dev Tools" and "Grok Constructor"

### ISSUE THREAD

**Issue by flysen** [stoerr/GrokConstructor#26]
Building a new pipeline via Kibana en "Dev Tools" I expect "**event**" to differ but it only assign **"event": "Event BorrowedDenied"** :

`POST _ingest/pipeline/_simulate
{
    "description": "To map license information via filebeat",
    "version" : 20170508,
    "pipeline" : {
    "processors" : [
              {
                "grok" : {
                  "field" : "message",
                  "patterns" : ["%{DATESTAMP:datetime} - ((?<event>Event BorrowedDenied)|(?<event>Event LicenceBorrowed)|(?<event>Event LicenceGrant)|(?<event>Event LicenceRenewed)|(?<event>Event LicenceReturn)) \"%{HOSTNAME:hostname}\" \"%{USER:user}\" program=\"%{GREEDYDATA:program}\" used=%{INT:used} available=%{INT:available} \\(tc=%{INT:tc}\\)"]
                }
              }
          ]
    },
    "docs" : [
    { 
      "_source" : {
      "message" : "04/05/2017 13:20:43 - Event LicenceBorrowed \"ITS-123456789\" \"jdoe\" program=\"Discover\" used=1 available=99 (tc=3)"
    }
    },
    { 
      "_source" : {
      "message" : "04/05/2017 13:20:41 - Event BorrowedDenied \"ITS-123456789\" \"jdoe\" program=\"Encom License Manager\" used=0 available=0 (tc=5)"
    }
    }
  ]
} `

Doing the same operation in Grok Constructor:
**Data**
`04/05/2017 13:20:43 - Event LicenceBorrowed "ITS-123456789" "jdoe" program="Discover" used=1 available=99 (tc=3)
04/05/2017 13:20:41 - Event BorrowedDenied "ITS-123456789" "jdoe" program="Encom License Manager" used=0 available=0 (tc=5)`

**GROK**
`%{DATESTAMP:datetime} - ((?<event>Event BorrowedDenied)|(?<event>Event LicenceBorrowed)|(?<event>Event LicenceGrant)|(?<event>Event LicenceRenewed)|(?<event>Event LicenceReturn)) \"%{HOSTNAME:hostname}\" \"%{USER:user}\" program=\"%{GREEDYDATA:program}\" used=%{INT:used} available=%{INT:available} \(tc=%{INT:tc}\)`

It parse the **event** into different values. I don't know if this i a bug or not but I need to start somewhere .

Cheers
Fredrik

**Comment by stoerr** [comment]
Sorry, I don't know about those dev tools, but I don't see anything wrong about the behaviour of grokconstructor. So I don't see what I could do here.
