### ISSUE TITLE
Error with asterisk in pattern 

### ISSUE THREAD

**Issue by mrjameshamilton** [stoerr/GrokConstructor#27]
Want to match:

`** WARNING ** You have enabled encryption but DISABLED certificate verification.`

with:

`\*\* %{LOGLEVEL:level} \*\* %{LS_MESSAGE:message1}`

but receive an error.

(works on https://grokdebug.herokuapp.com/ and within Logstash)

**Comment by stoerr** [comment]
Thanks for the bug report!

Sorry, I don't find any grok pattern LS_MESSAGE. Which pattern library is that from? If you use patterns defined in a personal pattern library, you need to provide those patterns in the "additional grop patterns" field.

BTW: please give the exact error message in bug reports. I assume you meant:
"This grok pattern has an unknown name LS_MESSAGE : %{LS_MESSAGE:message1}"

**Comment by mrjameshamilton** [comment]
Hi,

Sorry, yes LS_MESSAGE a custom pattern: `LS_MESSAGE .*`

It wasn't an unknown grok pattern error as I did provide the additional grok pattern but anway it seems to work now!

Thanks
