### ISSUE TITLE
Error display Chinese Characters in Matcher

### ISSUE THREAD

**Issue by wanglf** [stoerr/GrokConstructor#28]
After clicking go button, though log fields are parsed correctly, all Chinese characters display incorrect. I run **git clone** and **mvn clean install**  to build the standalone runnable jar file, use **java -jar GrokConstructor-0.1.0-SNAPSHOT-standalone.jar** to run the web application.

How to solve the encoding problem?

**Comment by stoerr** [comment]
Sorry, I have no idea why this happens and how to fix this. If someone has an idea, please tell me.

It seems to work with http://grokconstructor.appspot.com/ , though. Perhaps you can simply use the "official" site.

**Comment by wanglf** [comment]
okay, now kibana(after 5.5)  include a grokdebugger. I'll use that instead. 
Anyway, thanks very much.

https://www.elastic.co/guide/en/kibana/5.5/xpack-grokdebugger.html
