### ISSUE TITLE
Add support for modern Logstash/Grok field names encased in [..]

### ISSUE THREAD

**Issue by ThorbenJ** [stoerr/GrokConstructor#29]
re: http://grokconstructor.appspot.com/do/match

First: great tool, it has helped my a lot!

It appears that Logstash's modern variable name format [foo][bar][bob] (hash entry foo->bar->bob) is not supported by GrokConstructor, the following error message is give: "invalid char in group name"

Here is an example Grok for syslog RFC3164

```
<%{POSINT:[syslog][pri]:int}>%{SYSLOGTIMESTAMP:[syslog][timestamp]} +(?:%{IP:[rep][address]}|%{HOSTNAME:[rep][alias]}(?: +%{IP:[rep][ip]})?) +%{USERNAME:[@metadata][sl_type]}(?:\(%{PATH:[app][name]}\))?(?:\[%{POSINT:[proc][id]:int}\]?)?:? *%{GREEDYDATA:[msg]}"
```

This works correctly in Logstash 5.5.1, but not with GrokConstructor.

I would simply allow [, ] and @ in a substitute variable name (maybe masking them from an underlying library?).

At the moment, I have to strip them out (manually), do my debugging, then put them back in before copying to the final config.

**Comment by stoerr** [comment]
Thanks for the report; this should work now.
