### ISSUE TITLE
random page crash

### ISSUE THREAD

**Issue by ckozler** [stoerr/GrokConstructor#33]
Was messing with some grok tests. See here - https://pastebin.ca/3970948

**Comment by stoerr** [comment]
Hi!

 

Thanks! Couldn't you deduce your error from the error message? It says:

 



	
	Can't understand the following line in the additional grok patterns -
	
	
	it doesn't seem to be a normal line for a grok pattern file consisting of a key, a space and a definition. For example, this would be correct:
	
	
	# Some comment
	
	
	USERNAME [a-zA-Z0-9._-]+
	
	
	USER %{USERNAME}
	
	
	 
	
	
	The troublesome line is:
	
	
	 
	
	
	%{GREEDYDATA:test}\t%{IP:BRO_DNS_SRC_IP}\t%{INT:BRO_DNS_SRC_PORT}\t%{IP:BRO_DNS_SRC_IP}\t%{INT:BRO_DNS_SRC_PORT}\t%{GREEDYDATA:junk}
	


I was hoping that would be enough for people to figure out what they put into the wrong field.

 

Best regards,

 

Hans-Peter



 

Gesendet: Samstag, 10. Februar 2018 um 22:44 Uhr
Von: "Charles Kozler" <notifications@github.com>
An: stoerr/GrokConstructor <GrokConstructor@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [stoerr/GrokConstructor] random page crash (#33)


Was messing with some grok tests. See here - https://pastebin.ca/3970948

**Comment by ckozler** [comment]
Honestly it probably is but perhaps maybe something a little more direct or a note like "Perhaps you put your Grok pattern in the wrong field?" or something to that effect wouldnt hurt? Or maybe instead of it generating an error page when you know its probably in the wrong field you could pop a box up?

You're probably totally right that the current handling and error message is sufficient but I dont mess with Grok or anything all that often and was doing something with graylog so I needed this fantastically helpful tool

**Comment by stoerr** [comment]
Ah, I see, I added something like that in the meantime. So that was already done.
