### ISSUE TITLE
Dúvida Parsear log ELK

### ISSUE THREAD

**Issue by ldpereira-123** [stoerr/GrokConstructor#37]
I will try to explain my need, I get the complete log of an application that is multilinhas, so I understood filebeat does the reading by document base, in this way each line it "breaks" in the visualization; I need some logs that are on separate lines to be unique in Kibana, it would not be a problem if they were in the "message" field, but I need to extract the information with a set of Fields. Ex: Log1 AND Log2 AND Log3, as it stands today the contents of this "log" are in separate fields, which does not help me when searching for the expression in kibana.

Attached I am sending you the configuration of filebeat and logstash, I have not modified anything in the structure of the two; is sending all the log to the elasticsearch.

What I really need is to take this log and extract some information from it, I'll also send you the log by attachment and explain below what I'd like to do with the reported snippet (I've just changed the contents of the fields because I'm being given stealth)

I need the fields "tef_iso" to "Bit_127" to be unique, being displayed in only one message.

[logstash (1).txt](https://github.com/stoerr/GrokConstructor/files/2694879/logstash.1.txt)
[log_aplicacao (1).txt](https://github.com/stoerr/GrokConstructor/files/2694880/log_aplicacao.1.txt)
[filebeat_configuracao (1).txt](https://github.com/stoerr/GrokConstructor/files/2694881/filebeat_configuracao.1.txt)

**Comment by stoerr** [comment]
I'm sorry, that's probably a misunderstanding: this is only for reporting bugs and suggesting features for GrokConstructor http://grokconstructor.appspot.com . You are invited to use GrokConstructor for configuring the grok filter in your logstash.config , but I can't support you there. GrokConstructor is a sparetime project - I'm not involved with Elastic https://www.elastic.co/ , who created the fabulous ELK Stack, in any way.
