### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by rggassner** [stoerr/GrokConstructor#38]
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

Using the command:

 docker build -t grokconstructor .

I get the following error:

Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar (63 KB at 52.7 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:27 min
[INFO] Finished at: 2019-03-25T19:21:19+00:00
[INFO] Final Memory: 16M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project GrokConstructor: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /app && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /app/target/surefire/surefirebooter4385982829423115196.jar /app/target/surefire/surefire6109931819202034881tmp /app/target/surefire/surefire_05629268019846747388tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command '/bin/sh -c mvn clean install' returned a non-zero code: 1

**Comment by stoerr** [comment]
Thank you for reporting! I don't use the docker container anymore, so that'd be difficult for me to fix and add no value to https://grokconstructor.appspot.com/ . So if anybody wants to contribute a fix, that's invited, but I don't have time to do that.
