### ISSUE TITLE
Error parsing simple line

### ISSUE THREAD

**Issue by LordManzana** [stoerr/GrokConstructor#39]
To reproduce:

Log line:
30/01/2020 15:53:24.547\tYULEMATH\tGCO\\SRVINTITSMDES\tARQ.AppInt.JiraItsm.BE\tIntegracion\tIntegracion\t98441013-d58f-40d3-8fab-30320c3d4590\t-\tINF\tDescripción: 

Steps:
DATESTAMP
\\t
WORD

> Error message: java.util.NoSuchElementException: None.get
> 
> Time: Thu Jan 30 08:40:53 UTC 2020
> 
> RequestId: null
> 
> Request Info:
> ReqInfo for 5e32969500ff0a62e497e38d580001737e67726f6b636f6e7374727563746f7200013600010104 : {
>   "_url":"/do/constructionstep",
>   "groklibs":[
>     "firewalls",
>     "aws",
>     "bro",
>     "exim",
>     "bind",
>     "haproxy",
>     "linux-syslog",
>     "squid",
>     "mcollective-patterns",
>     "bacula",
>     "postgresql",
>     "java",
>     "maven",
>     "grok-patterns",
>     "httpd",
>     "redis",
>     "nagios",
>     "rails",
>     "mongodb",
>     "ruby",
>     "mcollective",
>     "junos"
>   ],
>   "loglines":[
>     "30/01/2020 15:53:24.547\\tYULEMATH\\tGCO\\\\SRVINTITSMDES\\tARQ.AppInt.JiraItsm.BE\\tIntegracion\\tIntegracion\\t98441013-d58f-40d3-8fab-30320c3d4590\\t-\\tINF\\tDescripción: "
>   ],
>   "nextPart":[
>     "%{HOSTNAME}"
>   ],
>   "pattern":[
>     "\\A%{DATESTAMP}\\\\t",
>     "\\A%{DATESTAMP}\\\\t"
>   ],
>   "submit":[
>     "Continue!"
>   ]
> }
> 
> 
> java.util.NoSuchElementException: None.get
> 	at scala.None$.get(Option.scala:347)
> 	at scala.None$.get(Option.scala:345)
> 	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:28)
> 	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:26)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:25)
> 	at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:81)
> 	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:53)
> 	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
> 	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
> 	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:539)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
> 	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
> 	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
> 	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:757)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:720)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:690)
> 	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:882)
> 	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by stoerr** [comment]
Shortest way to reproduce this: line a\tb and %{WORD}\t%{WORD} . (!Actual \t , not a real tab.)
