### ISSUE TITLE
Error when parsing Snare syslog events in matcher and Inc constructor

### ISSUE THREAD

**Issue by th3wyatt** [stoerr/GrokConstructor#40]
Whenever trying to parse Snare syslog events, the constructor and matcher both fail.  

Log contents:  
`MSWinEventLog#0115#011Security#0 Jun 29 20:53:35 2020#0115140#011Microsoft-Windows-Security-Auditing`

custom patterns:
`VT #011`

pattern to match
`MSWinEventLog%{VT}%{INT:crit}%{VT}%{WORD:event_src}%{VT}`

When attempting in the inc. constructor, there is a java exception. (https://pastebin.com/k6r8kbM4)

When attempting in matcher, the pattern is missing in the results and the match fails

![Screen Shot 2020-06-29 at 5 00 31 PM](https://user-images.githubusercontent.com/6827359/86067914-d9947780-ba2a-11ea-9515-4b21279ed8f8.png)

**Comment by stoerr** [comment]
Thank you for reporting this! That should have a more sensible error message, indeed. I'm closing this to clean up, since it's the same problem as https://github.com/stoerr/GrokConstructor/issues/39 , and would be fixed at the same time.
