### ISSUE TITLE
Multiline seems to break with predefined patterns

### ISSUE THREAD

**Issue by dschneller** [stoerr/GrokConstructor#5]
Thanks for the valuable tool. I stumbled across this issue, today, though:

This is my pattern:

```
(?m)^%{TIMESTAMP_ISO8601:timestamp} %{SYSLOGHOST:host} \[%{PROG:program}\]: \[%{NOTSPACE:application_thread}\] (?<loglevel>ALL|DEBUG|ERROR|FATAL|INFO|OFF|TRACE|WARN) %{JAVACLASS:class} - %{GREEDYDATA:message}?
```

This is some test data:

```
2015-04-10T06:57:41+02:00 192.168.205.14 [myapp]: [CD-DocumentServerThread-1] INFO d.c.c.d.job.StatusAwareTask - Executing something
2015-04-10T06:57:41+02:00 192.168.205.14 [myapp]: [CD-DocumentServerThread-1] DEBUG d.c.c.d.job.StatusAwareTask - Something took 0.114 seconds
2015-04-10T06:57:41+02:00 192.168.205.13 [otherapp]: [http-nio-8081-exec-28] ERROR d.c.c.r.p.m.ThrowableMapper - Something went wrong
java.lang.NullPointerException: null
2015-04-10T06:57:41+02:00 192.168.205.13 [myapp]: [CD-DocumentServer-Dispatcher] DEBUG d.c.c.d.server.Dispatcher - Received something
```

I noticed that when I put this into the multiline filter, with negate checked: 

```
^%{TIMESTAMP_ISO8601}%{SPACE}
```

all lines get sucked into the first one, mangled into the message field.

Next I tried this to narrow down my problem: 

```
^2015-04-10T06:57:41\+02:00 
                           ^ There is a space here
```

which works correctly, joining the `java.lang.NullPointerException: null` line into the previous one, leaving the rest intact.

Finally, this also breaks:

```
^2015-04-10T06:57:41\+02:00%{SPACE}
```

So it seems, the predefined library patterns are not working with the multiline feature. I could not find if this is not supposed to work (as per logstash documentation it seems it should), so I assume this is a bug in your implementation?

**Comment by lhoss** [comment]
Hi!
I stumbled on the same 'issue'.
I guess it's more a missing feature, as the multine expression indeed seems to only support a simple 'regex' as the form field title suggests ("... please specify the used regex:")
But it would indeed be useful to support the same default logstash patterns (+custom ones entered) in the multiline feature!

In my case to parse following 2 log lines:

```
2015-04-24 14:44:35,300 WARN  tera.core.Api$: Cannot read raw events from 'hdfs://hw03/data/etl/sc/2015/03/11'
        at data.hdfs.HdfsAvroReader.readRdd(HdfsAvroReader.scala:56)
```

It only worked by 'exploding' the multiline regex to:

```
\s+at\s+((?:[a-zA-Z0-9-]+\.)+[A-Za-z0-9$_]+.*)
```

did not work with my original 1.try, where I used existing patterns:
`\s*%{JAVASTACKTRACEPART}`

nor 2.try, where I added the JAVACLASS pattern myself to the 'additional grok patterns' field:
 `\s*at %{JAVACLASS:class}\.*`

Notes:
1) 'JAVASTACKTRACEPART' is a pattern defined in the default 'java' patterns: https://github.com/elastic/logstash/blob/v1.4.2/patterns/java  

```
JAVASTACKTRACEPART at %{JAVACLASS:class}\.%{WORD:method}\(%{JAVAFILE:file}:%{NUMBER:line}\)
```

2) My 'The pattern that should match all logfile lines:':

```
^\s*%{TIMESTAMP_ISO8601:timestamp}\s*%{LOGLEVEL:level}\s* (?:(%{USERNAME:thread} %{JAVACLASS:logger}|%{USERNAME:thread} {WORD:logger}|%{JAVACLASS:logger}|%{WORD:logger})): (?<content>(.|\r|\n)*)
```

**Comment by stoerr** [comment]
Thanks for the excellent bug report! 
Yes, you are right - multline did not yet support grok patterns. Perhaps it didn't when I built this. Anyway - now it does support it.
