### ISSUE TITLE
Radio buttons on the incremental constructor all have the same id, making labels useless

### ISSUE THREAD

**Issue by elyscape** [stoerr/GrokConstructor#8]
On properly-constructed forms, clicking on a radio button or checkbox's label will cause the associated element to be activated. Unfortunately, in the incremental constructor, all form elements have an `id` attribute of "nextPart". As a result, clicking on any radio button's label causes the first radio button to become selected. For radio buttons, the `name` attribute is what determines which radio buttons are linked, not the `id` attribute. Making each radio button have a unique `id` attribute would resolve this problem.

**Comment by stoerr** [comment]
Did you really have trouble working with the form? With what browser? I just tried again an example
http://grokconstructor.appspot.com/do/construction?example=1
both with Firefox and Chrome, and had no trouble constructing a regex. Admittedly, the equal ids are quite pointless and not conformant with HTML guidelines, but don't hurt the actual function: as long as the name and value are appropriate, the form works as it should.

**Comment by elyscape** [comment]
It works, but when I click on the text reading, for example, `%{GREEDYDATA}`, my browser instead selects the very first radio button, which is labeled `»"«`. As a result, I have to specifically click on the radio buttons, rather than being able to use the labels as well.

**Comment by elyscape** [comment]
As for which browser, I use Chrome, but this issue will affect pretty much every browser.

**Comment by stoerr** [comment]
Good point, thank you!
